services:
  postgres:
    image: postgres:16.1
    container_name: chat-postgres-DEV
    environment:
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PWD}
      POSTGRES_DB: myprojectdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_chat_DEV:/var/lib/postgresql/data

  pgadmin:
    container_name: chat-pgadmin-DEV
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@domain.com
      PGADMIN_DEFAULT_PASSWORD: root

volumes:
  postgres_chat_DEV: